spring:
  application:
    name: service
  aop:
    auto: true
eureka:
  client:
    serviceUrl:
       defaultZone: http://peer1:8081/eureka/,http://peer2:8082/eureka/,
  fetch-registry: true
  register-with-eureka: true
server:
  port: 8084
#instance:
#  metadata-map:
#    user.name: admin
#    user.password: admin
