eureka:
  client:
    serviceUrl:
       defaultZone: http://peer1:8081/eureka/,http://peer2:8082/eureka/,
spring:
  application:
    name: gateway
server:
  port: 8083
#zuul:
#  routes:
#    api-a-url.path: /service/**
#    api-a-url.serviceId: service
#    api-b-url.path: /service/**
#    api-b-url.serviceId: service
#  zuul.routes.api-a-url.path=/user/**
#  zuul.routes.api-a-url.serviceId=user-service
#
#  zuul.routes.api-b-url.path=/user/**
#  zuul.routes.api-b-url.serviceId=user-service
zuul:
  routes:
    service: /service/**
#instance:
#  metadata-map:
#    user.name: admin
#    user.password: admin
