#server:
#  port: 8082
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://peer1:8081/
#spring:
#  application:
#    name: eureka-service
#  profiles:
#    active: peer1